version: '3.8'

services:
  msph-s3-static:
    container_name: msph-s3-static
    image: bitnami/minio:2023.9.27
    ports:
      - '${ENV_MSPH_STATIC_S3_API_PORT}:9000'
      - '${ENV_MSPH_STATIC_S3_PORT}:9001'
    environment:
      - 'MINIO_ROOT_USER=${ENV_MSPH_STATIC_S3_USERNAME}'
      - 'MINIO_ROOT_PASSWORD=${ENV_MSPH_STATIC_S3_PASSWORD}'
      - 'MINIO_DEFAULT_BUCKETS=static:public'
      - 'MINIO_SCHEME=http'
    volumes:
      - ./.volumes/s3:/bitnami/minio/data
      - ./s3-static:/s3-transfer
    healthcheck:
      test: 'curl --fail http://localhost:9000/minio/health/live || exit 1'
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - moonsphere-network

  msph-web-client:
    container_name: msph-web-client
    image: ${ENV_MSPH_DOCKERHUB_USERNAME}/msph-web-client-dev:latest
    ports:
      - '${ENV_MSPH_WEB_CLIENT_PORT}:80'
    pull_policy: always
    depends_on:
      msph-s3-static:
        condition: service_healthy
    networks:
      - moonsphere-network

  msph-landing-page:
    container_name: msph-landing-page
    image: ${ENV_MSPH_DOCKERHUB_USERNAME}/msph-landing-page-dev:latest
    ports:
      - '${ENV_MSPH_LANDING_PAGE_PORT}:80'
    pull_policy: always
    depends_on:
      msph-s3-static:
        condition: service_healthy
    networks:
      - moonsphere-network

networks:
  moonsphere-network:
    driver: bridge
