version: '3.8'

services:
  vsph-s3-static:
    container_name: vsph-s3-static
    image: bitnami/minio:2023.9.27
    ports:
      - '${ENV_VSPH_STATIC_S3_API_PORT}:9000'
      - '${ENV_VSPH_STATIC_S3_PORT}:9001'
    environment:
      - 'MINIO_ROOT_USER=${ENV_VSPH_STATIC_S3_USERNAME}'
      - 'MINIO_ROOT_PASSWORD=${ENV_VSPH_STATIC_S3_PASSWORD}'
      - 'MINIO_DEFAULT_BUCKETS=static:public'
      - 'MINIO_SCHEME=http'
    volumes:
      - ./.volumes/s3:/bitnami/minio/data
      - ./s3-static:/s3-transfer
    healthcheck:
      test: 'curl --fail http://localhost:9000/minio/health/live || exit 1'
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - visphere-network

  vsph-web-client:
    container_name: vsph-web-client
    image: ${ENV_VSPH_DOCKERHUB_USERNAME}/vsph-web-client-dev:latest
    ports:
      - '${ENV_VSPH_WEB_CLIENT_PORT}:80'
    pull_policy: always
    depends_on:
      vsph-s3-static:
        condition: service_healthy
    networks:
      - visphere-network

  vsph-landing-page:
    container_name: vsph-landing-page
    image: ${ENV_VSPH_DOCKERHUB_USERNAME}/vsph-landing-page-dev:latest
    ports:
      - '${ENV_VSPH_LANDING_PAGE_PORT}:80'
    pull_policy: always
    depends_on:
      vsph-s3-static:
        condition: service_healthy
    networks:
      - visphere-network

networks:
  visphere-network:
    driver: bridge
